apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# non-kubeflow
# - argocd-apps/metallb.yaml
# - argocd-apps/rook-ceph.yaml
# - argocd-apps/nginx.yaml
# - argocd-apps/nvidia-gpu-operator.yaml
- argocd-apps/istio.yaml
# kubeflow
- argocd-apps/admission-webhook.yaml
- argocd-apps/central-dashboard.yaml
- argocd-apps/certmanager.yaml
- argocd-apps/dex.yaml
- argocd-apps/kfam.yaml
- argocd-apps/knative.yaml
- argocd-apps/kubeflow-ns.yaml
- argocd-apps/kubeflow-pipelines.yaml
- argocd-apps/kubeflow-roles.yaml
- argocd-apps/notebook.yaml
- argocd-apps/oidc-auth.yaml
- argocd-apps/user-namespace.yaml
- argocd-apps/volumes.yaml

# - argocd-apps/experimental-pvcviewer-controller.yaml
# - argocd-apps/experimental-volumes-web-app.yaml
# Monitoring and logging
# - argocd-apps/monitoring-resources.yaml
# - argocd-apps/kube-prometheus-stack.yaml
# - argocd-apps/loki-stack.yaml
# - argocd-apps/kiali.yaml