apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-authservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vmallya-123/kubeflow-argo.git
    targetRevision: main
    path: common/oidc-authservice
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
