apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vmallya-123/kubeflow-argo.git
    targetRevision: main
    path: apps/training-operator/upstream/overlays/kubeflow
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
